version: '3.7'

services:

  phorest-app:
    container_name: phorest-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:2
    environment:
      SPRING_PROFILE_ACTIVE: docker
    ports:
      - 8080:8080
    depends_on:
      - phorest-app-postgres

  phorest-app-postgres:
    container_name: phorest-app-postgres
    image: library/postgres:latest
    environment:
      POSTGRES_USER: phorest-app
      POSTGRES_PASSWORD: phorest-app
      POSTGRES_DB: phorest-app
    ports:
      - 5432:5432
